//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessMyMessServer.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account has not been verified. Please, check your email..
        /// </summary>
        public static string Error_AccountNotVerified {
            get {
                return ResourceManager.GetString("Error_AccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load recent conversations..
        /// </summary>
        public static string Error_ConversationsFailed {
            get {
                return ResourceManager.GetString("Error_ConversationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database unavailable. Please try again later..
        /// </summary>
        public static string Error_DatabaseConnectionError {
            get {
                return ResourceManager.GetString("Error_DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving data to the database..
        /// </summary>
        public static string Error_DatabaseSave {
            get {
                return ResourceManager.GetString("Error_DatabaseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already registered..
        /// </summary>
        public static string Error_EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("Error_EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email format is not valid..
        /// </summary>
        public static string Error_EmailFormat {
            get {
                return ResourceManager.GetString("Error_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not send verification email..
        /// </summary>
        public static string Error_EmailSendFailed {
            get {
                return ResourceManager.GetString("Error_EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username/Email and password are required..
        /// </summary>
        public static string Error_FieldsRequired {
            get {
                return ResourceManager.GetString("Error_FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not retrieve friends list. Please try again..
        /// </summary>
        public static string Error_FriendListFailed {
            get {
                return ResourceManager.GetString("Error_FriendListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not retrieve friend requests..
        /// </summary>
        public static string Error_FriendRequestsFailed {
            get {
                return ResourceManager.GetString("Error_FriendRequestsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to retrieve game words. Please try again..
        /// </summary>
        public static string Error_GameWordsFailed {
            get {
                return ResourceManager.GetString("Error_GameWordsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect credentials..
        /// </summary>
        public static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid or expired verification code..
        /// </summary>
        public static string Error_InvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("Error_InvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error joining the lobby. Please try again..
        /// </summary>
        public static string Error_JoiningLobbyData {
            get {
                return ResourceManager.GetString("Error_JoiningLobbyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load chat history..
        /// </summary>
        public static string Error_MessageHistoryFailed {
            get {
                return ResourceManager.GetString("Error_MessageHistoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password does not meet the security requirements..
        /// </summary>
        public static string Error_PasswordInsecure {
            get {
                return ResourceManager.GetString("Error_PasswordInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected server error occurred..
        /// </summary>
        public static string Error_ServerGeneric {
            get {
                return ResourceManager.GetString("Error_ServerGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security warning: Session user mismatch..
        /// </summary>
        public static string Error_SessionMismatch {
            get {
                return ResourceManager.GetString("Error_SessionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is already in use..
        /// </summary>
        public static string Error_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Error_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found..
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while searching for users..
        /// </summary>
        public static string Error_UserSearchFailed {
            get {
                return ResourceManager.GetString("Error_UserSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User logged in successfully..
        /// </summary>
        public static string Info_LoginSuccess {
            get {
                return ResourceManager.GetString("Info_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration successful. A verification code has been sent..
        /// </summary>
        public static string Info_RegisterSuccess {
            get {
                return ResourceManager.GetString("Info_RegisterSuccess", resourceCulture);
            }
        }
    }
}
