//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectMessages
    {
        public int MessageID { get; set; }
        public int SenderPlayerID { get; set; }
        public int RecipientPlayerID { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
