//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int idFriendship { get; set; }
        public Nullable<int> Player_idPlayer1 { get; set; }
        public Nullable<int> Player_idPlayer2 { get; set; }
        public Nullable<int> FriendShipStatus_idFriendShipStatus { get; set; }
    
        public virtual FriendShipStatus FriendShipStatus { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
