//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuessMyMessDBEntities : DbContext
    {
        public GuessMyMessDBEntities()
            : base("name=GuessMyMessDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avatar> Avatar { get; set; }
        public virtual DbSet<Drawing> Drawing { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<FriendShipStatus> FriendShipStatus { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<KickVote> KickVote { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchDifficulty> MatchDifficulty { get; set; }
        public virtual DbSet<MatchHistory> MatchHistory { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetwork { get; set; }
        public virtual DbSet<TypeSocialNetwork> TypeSocialNetwork { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<Word> Word { get; set; }
        public virtual DbSet<WordDifficulty> WordDifficulty { get; set; }
        public virtual DbSet<DirectMessages> DirectMessages { get; set; }
    }
}
