//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KickVote
    {
        public int idKickVote { get; set; }
        public Nullable<byte> voteCast { get; set; }
        public Nullable<int> Player_idVoterPlayer { get; set; }
        public Nullable<int> Player_idTargetPlayer { get; set; }
        public Nullable<int> Match_idMatch { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
