//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Drawing = new HashSet<Drawing>();
            this.KickVote = new HashSet<KickVote>();
            this.MatchHistory = new HashSet<MatchHistory>();
        }
    
        public int idMatch { get; set; }
        public Nullable<int> maxPlayers { get; set; }
        public Nullable<int> currentPlayers { get; set; }
        public Nullable<int> totalRounds { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<byte> isPrivate { get; set; }
        public string matchCode { get; set; }
        public Nullable<int> Player_idHost { get; set; }
        public Nullable<int> MatchDifficulty_idMatchDifficulty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drawing> Drawing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KickVote> KickVote { get; set; }
        public virtual MatchDifficulty MatchDifficulty { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchHistory> MatchHistory { get; set; }
    }
}
