//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchHistory
    {
        public int idMatchHistory { get; set; }
        public Nullable<int> finalScore { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<int> Match_idMatch { get; set; }
        public Nullable<int> Player_idPlayer { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
