//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessMyMessServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        public int idSocialNetwork { get; set; }
        public string userLink { get; set; }
        public Nullable<int> Player_idPlayer { get; set; }
        public Nullable<int> TypeSocialNetwork_idTypeSocialNetwork { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual TypeSocialNetwork TypeSocialNetwork { get; set; }
    }
}
